services:
  postgres:
    image: postgres:15
    container_name: actas_sodimac
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Sodimac25*
      POSTGRES_DB: actas_sodimac
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_sodimac
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: Sodimac25*
    ports:
      - "5050:80"

  bk_actas_sodimac:
    build: .
    container_name: bk_actas_sodimac_app # Dale un nombre √∫nico a tu contenedor para evitar confusiones.
    # command: npm start # üí° Si tu Dockerfile no define un comando de inicio por defecto (CMD o ENTRYPOINT) o quieres sobrescribirlo, puedes especificarlo aqu√≠.
    # Cargar variables desde el archivo .env del proyecto para evitar valores hardcodeados
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://admin:Sodimac25*@postgres:5432/actas_sodimac
      PORT: 3000
    ports:
      - "3000:3000" # ‚úÖ **CR√çTICO:** Mapea el puerto 3000 de tu m√°quina host al puerto 3000 dentro del contenedor.
    depends_on:
      - postgres # ‚úÖ Asegura que el servicio `postgres` se inicie antes que tu backend, ya que el backend depende de la base de datos.
    volumes:
      - .:/app # ‚úÖ Mapea tu c√≥digo fuente local (directorio actual '.') al directorio '/app' dentro del contenedor. √ötil para desarrollo con Nodemon.
      - /app/node_modules # ‚úÖ **IMPORTANTE:** Esto excluye la carpeta `node_modules` del mapeo anterior para usar las dependencias instaladas dentro del contenedor, no las de tu host.
    restart: unless-stopped # ‚ú® Buena pr√°ctica: el contenedor intentar√° reiniciarse autom√°ticamente a menos que lo detengas manualmente.

volumes:
  postgres_data:
